### ISSUE TITLE
problem with a blank space

### ISSUE THREAD

**Issue by viktortrass** [smtdev/tautulli-telegram-notifications#2]
Hi,

I have a problem with telegram, when I set tautulli with your notification template for recently added content, in the part of poster url it show the characters "&nbsp" as a hyperlink for img url.

How can I set up poster url without showing this characters, just a blank space?

Thank you.

**Comment by apriliars3** [comment]
I have the same problem.

**Comment by smtdev** [comment]
@viktortrass @apriliars3 I didn't see this, sorry. You can simply remove the `&nbsp;` text from the template. For any reason, Tautulli app does not understand it as before. 

I've fixed it in the repository along with another issue regarding the `{year}` parameter in the templates, which does not work as expected in tv shows due to Plex issues. More info [here](https://github.com/Tautulli/Tautulli/issues/1588). You need to replace `{year}` to `{show_year}` in <episodes>, <show> and <season> tags.
